version: '3.8'

services:
  client:
    image: skaffaleclient-image
    build: ./client
    container_name: skaffaleclient-container
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - server

  server:
    image: skaffaleapi-image
    build: ./server
    container_name: skaffaleapi-container
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: postgres
    container_name: skaffaledatabase-container
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    container_name: skaffaleadminer-container
    restart: always
    ports:
      - 3001:8080